version: "3.1"
services:
    db:
        image: postgres:15
        environment:
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - POSTGRES_DB=postgres
        volumes:
            - ./postgresql:/etc/postgresql
        command: -c 'config_file=/etc/postgresql/postgresql.conf'
        networks:
            - backend

    odoo16:
        image: xmars/odoo16-cicd
        build:
            context: dockerfile
            dockerfile: Dockerfile
        depends_on:
            - db
        environment:
            - HOST=db
            - PORT=5432
            - USER=odoo
            - PASSWORD=odoo
        volumes:
            - ../../:/mnt/extra-addons # customize addons
            - ./et-addons:/mnt/et-addons # odoo enterprise addons.
            - ./etc:/etc/odoo
            - ./logs:/var/log/odoo
        networks:
            - backend

networks:
    backend:
        driver: bridge
